### ISSUE TITLE
[TM]: with some settings, dragging an item (e.g. mp3 from dolphin) to an open task (e.g. musicplayer) doesnt bring up program window

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.10#10]
works with most settings but not as follow:
![taskmanager_screenshot_20160803_134625](https://cloud.githubusercontent.com/assets/840070/17364534/fa75b2fc-5980-11e6-9fb9-05d82824d429.png)

**Comment by eikehein** [comment]
Can reproduce, looking into it

**Comment by eikehein** [comment]
Fixed in http://commits.kde.org/plasma-desktop/b87748c8ed29c1e8585d280cda63d770c25f6fba

Will be in 5.7.4 scheduled for August 23rd

**Comment by star-buck** [comment]
just checked this on kde neon 5.10 beta and it works :)
(i assume it has been long fixed, just as it wasnt marked green QA I overlooked it so far)
