### ISSUE TITLE
[packaging neon]: fail to install aptdaemon

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.10#18]
aptdaemon fails with this error:

> The following packages have unmet dependencies:
> python3-aptdaemon : Depends: gir1.2-packagekitglib-1.0 (< 0.9) but 1.1.0-2+16.04+build3 is to be installed
>                      Recommends: aptdaemon but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

**Comment by apachelogger** [comment]
why is it needed?

**Comment by ScarlettGatelyClark** [comment]
I can confirm this is broken. I am trying to go through some python3 lessons to fix up a project I am working on and got:

scarlett@scarlett-neon:~$ sudo apt install python3-aptdaemon
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) python3-aptdaemon [ amd64 ] < none -> 1.1.1+bzr982-0ubuntu14 > ( python )
Broken python3-aptdaemon:amd64 Depends on gir1.2-packagekitglib-1.0 [ amd64 ] < none -> 1.1.0-2+16.04+build3 > ( introspection ) (< 0.9)
  Considering gir1.2-packagekitglib-1.0:amd64 0 as a solution to python3-aptdaemon:amd64 9998
  Re-Instated gir1.2-packagekitglib-1.0:amd64
Broken python3-aptdaemon:amd64 Depends on python3-defer [ amd64 ] < none -> 1.0.6-2build1 > ( python ) (>= 1.0.6)
  Considering python3-defer:amd64 0 as a solution to python3-aptdaemon:amd64 9998
  Re-Instated python3-defer:amd64
Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-aptdaemon : Depends: gir1.2-packagekitglib-1.0 (< 0.9) but 1.1.0-2+16.04+build3 is to be installed
                     Recommends: aptdaemon but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Thanks

**Comment by nmabhinandan** [comment]
This is broken!

**Comment by star-buck** [comment]
@jriddell : a fix would be great for shipping in maui 2

**Comment by jriddell** [comment]
we update the packagekit in neon because discover needs a newer packagekit.  aptdaemon uses an old packagekit so the two don't like to be installed side-by-side.  A newer aptdaemon might be possible I'll investigate.  But I'm still unsure why this is needed.

**Comment by nmabhinandan** [comment]
New Intel graphics installer needs aptdaemon

**Comment by jriddell** [comment]
added aptdaemon to the archives and it seems to install
I can't test it since nobody has said what it's needed for and I don't know what the new intel graphics installer is

**Comment by jriddell** [comment]
discovered it at 
https://01.org/linuxgraphics/downloads/intel-graphics-update-tool-linux-os-v2.0.2
and it seems to work as expected
(although you need to set DISTRIBUTOR_ID=Ubuntu in /etc/lsb-release sigh

**Comment by nmabhinandan** [comment]
👍👌

**Comment by star-buck** [comment]
i still get : 
aptdaemon : Depends python3-aptdaemon (=1.1.1+bzr982-0ubuntu14) but it is not going to be installed

**Comment by jriddell** [comment]
what does it say if you  apt install python3-aptdaemon  ?
