### ISSUE TITLE
[splashscreen, looknfeel, window deco kcm]: selection marker _jumps_ through all entries before "landing on the current selected entry"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.10#33]
places seen this:
wallpaper dialog, desktop theme kcm, lookandfeel theme

**Comment by notmart** [comment]
If i understood correctly, the issue is that in those kcms the selected item looks like it's the first for a moment, then the proper one gets selected afterwards, sometimes causing scroll of the view, right?

**Comment by star-buck** [comment]
Right, mostly doing a "wheel of fortune" spinning the marker forward until it lands on the active one.

**Comment by notmart** [comment]
I think i found out where the issue lies. I still have to do some tests for a couple of possible fixes, but should be fixable without any graphics glitch left

**Comment by notmart** [comment]
Tentative fixes landed and ready to be tested
fix for l&f kcm: https://cgit.kde.org/plasma-desktop.git/commit/?id=ee2ec66a415580a5c4ccfdb34e5f6e68a7739652
plasma theme kcm: https://commits.kde.org/plasma-desktop/d9d52a37c6ba267f7da936c0436b254788f7cb87
wallpaper: https://commits.kde.org/plasma-workspace/5434e4bc014181841df0e24979e03288584b8696
(latter one should solve https://github.com/blue-systems/plasma-5.8/issues/32 as well)

**Comment by star-buck** [comment]
still jumps on:
- splash screen kcm
-

**Comment by star-buck** [comment]
also window deco still jumps

**Comment by star-buck** [comment]
tested on neon5.9 and still those two kcm selection markers "jump"

**Comment by notmart** [comment]
splash screen kcm fixed on master

**Comment by notmart** [comment]
for kwin https://phabricator.kde.org/D4703

**Comment by notmart** [comment]
fixes laded, should be testable on devel edition
