### ISSUE TITLE
[sddm]: login screen rejects jpg format for avatars (only allows png?)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.10#41]
User reported this here: http://forums.mauilinux.org/showthread.php?tid=24140
Is this a global issue and can be fixed in sddm or is it theme related?

**Comment by davidedmundson** [comment]
It seems to be a non issue.

1) UserManager will always save ~/.face as a PNG

2) SDDM will load .jpg files just fine. I just tested it on SDDM's default theme, and Breeze.

I haven't explicitly tested Maui's theme, but I can't see why it would be different. It would take more work to break it.

So the user is getting confused, he's also talking about a directory that doesn't get used by SDDM.
I'll reply on the forum with a comment on what gets loaded from where, and hopefully that'll fix whatever problem he's in.

**Comment by star-buck** [comment]
Great thanks!
