### ISSUE TITLE
Widgets: Comic Strips is displayed under "Graphics", would fit better under "Fun and Games"(?)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.10#44]
![screenshot_20170112_214408](https://cloud.githubusercontent.com/assets/840070/21907553/44d20080-d910-11e6-9dd1-d1c33ad9c695.png)

**Comment by notmart** [comment]
moved it to fun&games in master

**Comment by star-buck** [comment]
which version would this be in?

**Comment by notmart** [comment]
will be in Plasma 5.10, out on 30th of May

**Comment by star-buck** [comment]
5.10 beta done
